"""day table

Revision ID: 9add76c067fb
Revises: 
Create Date: 2018-06-19 19:21:30.867415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9add76c067fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('month', sa.String(length=64), nullable=True),
    sa.Column('day', sa.String(length=64), nullable=True),
    sa.Column('maxtemp', sa.Float(), nullable=True),
    sa.Column('mintemp', sa.Float(), nullable=True),
    sa.Column('avetemp', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day')
    # ### end Alembic commands ###
