"""new tables

Revision ID: a30707716cc7
Revises: 
Create Date: 2018-06-28 15:10:09.244136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30707716cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('month', sa.String(length=64), nullable=True),
    sa.Column('day', sa.String(length=64), nullable=True),
    sa.Column('maxtemp', sa.Float(), nullable=True),
    sa.Column('mintemp', sa.Float(), nullable=True),
    sa.Column('avetemp', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature')
    op.drop_table('rain')
    op.drop_table('day')
    # ### end Alembic commands ###
